### ISSUE TITLE
error with xmpp

### ISSUE THREAD

**Issue by nicdoesstuff69** [Project-Reload/Reload-Backend#47]
Reload Debug Log: Request to /fortnite/api/storefront/v2/keychain
Reload Debug Log: GET /fortnite/api/receipts/v1/account/*/receipts called
Unhandled promise rejection: TypeError: Cannot read properties of null (reading 'list')
    at D:\oldfn build\basebackend\Backend\MPBackend\routes\friends.js:211:33
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) Promise {
  <rejected> TypeError: Cannot read properties of null (reading 'list')
      at D:\oldfn build\basebackend\Backend\MPBackend\routes\friends.js:211:33
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
}
Reload Debug Log: GET /socialban/api/public/v1/* called
Unhandled promise rejection: TypeError: Cannot read properties of null (reading 'list')
    at D:\oldfn build\basebackend\Backend\MPBackend\routes\friends.js:70:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) Promise {
  <rejected> TypeError: Cannot read properties of null (reading 'list')
      at D:\oldfn build\basebackend\Backend\MPBackend\routes\friends.js:70:13
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
}
Reload Debug Log: GET /socialban/api/public/v1/* called
Reload Debug Log: Request to /fortnite/api/storefront/v2/catalog
Reload Debug Log: POST /datarouter/api/v1/public/data called
Reload Debug Log: Missing endpoint: GET /content-controls/90b2049e3e134be4aecb7c6f26372347 request port 3551
Reload Debug Log: GET /api/v1/events/Fortnite/download/* called
Reload Debug Log: ALL /fortnite/api/game/v2/profileToken/verify/90b2049e3e134be4aecb7c6f26372347 called
Reload Debug Log: GET /account/api/public/account/displayName/friend called
Reload Debug Log: GET /account/api/public/account called
Reload Debug Log: POST /api/v1/user/setting called
Unhandled promise rejection: TypeError: Cannot read properties of null (reading 'list')
    at D:\oldfn build\basebackend\Backend\MPBackend\routes\friends.js:211:33
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) Promise {
  <rejected> TypeError: Cannot read properties of null (reading 'list')
      at D:\oldfn build\basebackend\Backend\MPBackend\routes\friends.js:211:33
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
}
Unhandled promise rejection: TypeError: Cannot read properties of null (reading 'list')
    at D:\oldfn build\basebackend\Backend\MPBackend\routes\friends.js:70:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) Promise {
  <rejected> TypeError: Cannot read properties of null (reading 'list')
      at D:\oldfn build\basebackend\Backend\MPBackend\routes\friends.js:70:13
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
}
Reload Debug Log: GET /account/api/oauth/verify called for account: 90b2049e3e134be4aecb7c6f26372347

keeps on doing some crap with the friends list and it says unknown error every time i try to add someone

**Comment by nicdoesstuff69** [comment]
i even tried 2 other versions of reload, i still get this 
![image](https://github.com/user-attachments/assets/172d5675-24e1-4d9a-bb3a-fe255a1218e8)

**Comment by burlone0** [comment]
in which season it gave u this error?

**Comment by nicdoesstuff69** [comment]
i fixed it, will there ever be tcp xmpp?

**Comment by burlone0** [comment]
how do u fix?
